/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Pixelify Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        pixel: ['"Pixelify Sans"', 'monospace'],
        display: ['Cinzel', 'Georgia', 'serif'],
        vn: ['"Pixelify Sans"', 'monospace'],
      },
      colors: {
        sidebar: {
          DEFAULT: '#fff9e6',
          hover: '#f5ecd0',
          border: '#e8dcc0',
          text: '#2d2d2d',
          muted: '#888888',
        },
        cream: {
          50: '#2d2d2d',
          100: '#fff9e6',
          200: '#2d2d2d',
        },
        accent: {
          DEFAULT: '#2d2d2d',
          light: '#2d2d2d',
          dark: '#666666',
          hover: '#666666',
        },
        petzen: {
          teal: '#2d2d2d',
          'teal-bright': '#2d2d2d',
          'teal-deep': '#666666',
          orange: '#2d2d2d',
          'orange-bright': '#2d2d2d',
          yellow: '#2d2d2d',
          cream: '#fff9e6',
          'cream-2': '#2d2d2d',
          'cream-3': '#f5ecd0',
        },
        chat: {
          user: '#f5ecd0',
          assistant: '#2d2d2d',
          border: '#e8dcc0',
          input: '#2d2d2d',
        },
        dark: {
          bg: '#fff9e6',
          surface: '#2d2d2d',
          elevated: '#f5ecd0',
          border: '#e8dcc0',
          text: '#2d2d2d',
          muted: '#888888',
          accent: '#2d2d2d',
          'accent-bright': '#2d2d2d',
          'user-bubble': '#e8dcc0',
          'assistant-bubble': '#2d2d2d',
        },
        vn: {
          stage: '#fff9e6',
          stageLight: '#2d2d2d',
          dialogue: '#2d2d2d',
          dialogueBorder: '#e8dcc0',
          name: '#2d2d2d',
          nameGlow: '#2d2d2d',
          text: '#2d2d2d',
          textDim: '#888888',
          highlight: '#2d2d2d',
          cooldown: '#2d2d2d',
        },
      },
      maxWidth: { chat: '48rem' },
      animation: {
        'vn-fade-in': 'vn-fade-in 0.5s ease-out forwards',
        'vn-slide-up': 'vn-slide-up 0.4s ease-out forwards',
        'vn-portrait-in': 'vn-portrait-in 0.6s ease-out forwards',
        'vn-glow': 'vn-glow 2.5s ease-in-out infinite',
        'vn-shimmer': 'vn-shimmer 0.6s ease-out forwards',
      },
      keyframes: {
        'vn-fade-in': { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        'vn-slide-up': { '0%': { opacity: 0, transform: 'translateY(12px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        'vn-portrait-in': { '0%': { opacity: 0, transform: 'scale(0.92)' }, '100%': { opacity: 1, transform: 'scale(1)' } },
        'vn-glow': { '0%, 100%': { opacity: 0.6 }, '50%': { opacity: 1 } },
        'vn-shimmer': { '0%': { opacity: 0.5 }, '100%': { opacity: 1 } },
      },
      boxShadow: {
        vn: '0 0 60px -12px rgba(102, 188, 180, 0.32), 0 25px 50px -12px rgba(42, 31, 18, 0.15)',
        'vn-inner': 'inset 0 2px 20px 0 rgba(102, 188, 180, 0.1)',
        portrait: '0 25px 50px -12px rgba(42, 31, 18, 0.2), 0 0 0 1px rgba(102, 188, 180, 0.22)',
      },
    },
  },
  plugins: [],
}
