"""add dialogue_act and ml_metadata to messages

Revision ID: 69625113f9bb
Revises: d4e8f9012abc
Create Date: 2026-05-09 19:35:41.609896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69625113f9bb'
down_revision: Union[str, Sequence[str], None] = 'd4e8f9012abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('dialogue_act', sa.String(length=128), nullable=True))
    op.add_column('messages', sa.Column('ml_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'ml_metadata')
    op.drop_column('messages', 'dialogue_act')
    # ### end Alembic commands ###
